coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%

comment:
  layout: "header, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
  hide_project_coverage: false
